### ISSUE TITLE
GDB fails to build with Python 3.7

### ISSUE THREAD

**Issue by maxthest** [devkitPro/buildscripts#32]
The build script is failing to compile GDB 8.0 because of a recent change in the Python API since 3.7.

> ../../../gdb-8.0/gdb/python/python.c: In function ‘bool do_start_initialization()’:
../../../gdb-8.0/gdb/python/python.c:1584:45: error: too few arguments to function ‘int _PyImport_FixupBuiltin(PyObject*, const char*, PyObject*)’
   _PyImport_FixupBuiltin (gdb_module, "_gdb");
                                             ^
In file included from /usr/include/python3.7m/Python.h:126,
                 from ../../../gdb-8.0/gdb/python/python-internal.h:94,
                 from ../../../gdb-8.0/gdb/python/python.c:94:
/usr/include/python3.7m/import.h:115:17: note: declared here
 PyAPI_FUNC(int) _PyImport_FixupBuiltin(
                 ^~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:1914: python.o] Error 1
make[2]: Leaving directory '/home/arch-linux-user/.cache/makepkg/devkitarm/src/buildscripts/.devkitARM/arm-none-eabi/gdb/gdb'
make[1]: *** [Makefile:9126: all-gdb] Error 2
make[1]: Leaving directory '/home/arch-linux-user/.cache/makepkg/devkitarm/src/buildscripts/.devkitARM/arm-none-eabi/gdb'
make: *** [Makefile:849: all] Error 2
Error building gdb
[arch-linux-user@arch-linux-host devkitarm]$ pacman -Q python
python 3.7.0-3
[arch-linux-user@arch-linux-host devkitarm]$ 

GDB upstream has fixed this since 8.1 however this toolchain uses 8.0, thus the GDB patches will need to be modified to include this fix.
See this link for details:
[https://bugzilla.redhat.com/show_bug.cgi?id=1577396](https://bugzilla.redhat.com/show_bug.cgi?id=1577396)

**Comment by WinterMute** [comment]
We recommend https://devkitpro.org/wiki/devkitPro_pacman rather than using these buildscripts yourself.

We have things tuned so binaries run fine on a variety of linux distros although arch needs ncurses5-compat-libs which is kind of annoying.

Unfortunately 8.1. is currently broken when building for windows.

**Comment by maxthest** [comment]
Hi WinterMute,

While I appreciate the recommendation, the problem will still remain and, at least, should be documented and triaged.
I also want to build the devkitPro toolchain with custom build flags, such as hardening, and there will be others who would like to do the same for their environments.

As you pointed out, the distributed binaries require ncurses with ABI 5, which can be inconvenient for Arch Linux and other distributions such as Fedora. Building GDB in the toolchain will link with the system installed ncurses library which does not have to be ABI 5.

The MSys2 project has a PKGBUILD script that builds GDB version 8.1.1 for Windows that may be useful to you or any other contributor. Here is the link to the script:
https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-gdb/PKGBUILD

Again, thank you for the suggestion.

**Comment by maxthest** [comment]
Tested the build process and confirmed. Toolchain's GDB builds with latest Python version. Closing this issue. Thank you for your dedication to this project.
